name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-12
            swift: "5.7"

    steps:
      - run: swift --version
      - uses: actions/checkout@v3
      - run: swift test
      - uses: actions/upload-artifact@v3
        with:
          name: sample-xcassets
          path: SampleApp
      - run: swift build -c release
